[project]
name = "leetcode75"
version = "0.1.0"
description = "LeetCode top 75 interview questions"
requires-python = ">=3.13"
dependencies = []
[project.optional-dependencies]
test = [
    "pytest==8.4.2",
    "pytest-cov==7.0.0",
]
dev = [
    "pre-commit==4.4.0",
]